name: Build Android APK with Buildozer

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev python3-pip git wget unzip
        pip install cython
        pip install buildozer
        pip install python-for-android

    - name: Install Android SDK Command Line Tools
      run: |
        sudo apt-get install -y openjdk-8-jdk
        mkdir -p "$HOME/android-sdk/cmdline-tools"
        cd "$HOME/android-sdk"
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

    - name: Install Android SDK components
      run: |
        echo "Installing required SDK components..."
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "platform-tools" "platforms;android-30"
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;36.0.0"  # Adjust version as needed

    - name: Attempt non-interactive license acceptance
      run: |
        echo "Attempting non-interactive license acceptance..."
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses

    - name: Fallback to interactive license acceptance (if needed)
      run: |
        echo "Attempting interactive license acceptance if non-interactive fails..."
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
      continue-on-error: true  # Allow this step to fail without stopping the workflow

   

    - name: Run Buildozer to build the APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
        buildozer android debug

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
