name: Build Android APK with Buildozer

on:
  push:
    branches:
      - main  # Trigger this action when there's a push to the main branch
  pull_request:
    branches:
      - main  # Trigger this action on pull requests to the main branch

jobs:
  build:
    runs-on: ubuntu-latest  # Use an Ubuntu runner to build the app

    steps:
    - name: Checkout code
      uses: actions/checkout@v2  # Checkout your code from GitHub

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.8'  # Specify the version of Python to use

    - name: Install Buildozer dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev python3-pip git wget unzip
        pip install cython
        pip install buildozer
        pip install python-for-android

    - name: Install Android SDK Command Line Tools
      run: |
        sudo apt-get install -y openjdk-8-jdk
        mkdir -p "$HOME/android-sdk/cmdline-tools"
        cd "$HOME/android-sdk"
        wget https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O cmdline-tools.zip
        unzip cmdline-tools.zip -d cmdline-tools
        mv cmdline-tools/cmdline-tools cmdline-tools/latest
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$PATH

    - name: Accept Android SDK licenses
      run: |
        yes | $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager --licenses
        $ANDROID_SDK_ROOT/cmdline-tools/latest/bin/sdkmanager "build-tools;36.0.0" "platform-tools" "platforms;android-30"

    - name: Clean previous build
      run: |
        # Run Buildozer clean to remove any old artifacts
        buildozer android clean

    - name: Run Buildozer to build the APK
      run: |
        export ANDROID_SDK_ROOT=$HOME/android-sdk
        export PATH=$ANDROID_SDK_ROOT/cmdline-tools/latest/bin:$ANDROID_SDK_ROOT/platform-tools:$PATH
        # Run Buildozer to build the APK
        buildozer android debug  # Replace with android release for production

    - name: Upload APK as artifact
      uses: actions/upload-artifact@v4
      with:
        name: android-apk
        path: bin/*.apk
