name: Build Android APK with Buildozer

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4  # Use latest stable version

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.8'

      - name: Install Buildozer dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential libssl-dev libffi-dev python3-dev python3-pip
          pip install --upgrade pip
          pip install cython
          pip install buildozer
          pip install python-for-android

      - name: Install Android dependencies
        run: |
          sudo apt-get install -y openjdk-8-jdk unzip zip
          echo "JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64" >> $GITHUB_ENV
          echo "PATH=$JAVA_HOME/bin:$PATH" >> $GITHUB_ENV

      - name: Run Buildozer
        run: |
          buildozer android debug

      - name: List APK files
        run: ls -al bin/

      - name: Upload APK
        uses: actions/upload-artifact@v4  # ✅ Use v4
        with:
          name: android-apk
          path: bin/*.apk
